const menuItems = [
  {
    keyword: 'gaspacho',
    name: 'Гаспачо',
    price: 195,
    category: 'soup',
    count: '350 г',
    image: 'img/gaspacho.jpg',
    kind: 'veg',
  },
  {
    keyword: 'mashroom_soup',
    name: 'Грибной суп-пюре',
    price: 185,
    category: 'soup',
    count: '330 г',
    image: 'img/mashroom_soup.jpg',
    kind: 'veg',
  },
  {
    keyword: 'norway_soup',
    name: 'Норвежский суп',
    price: 270,
    category: 'soup',
    count: '330 г',
    image: 'img/norway_soup.jpg',
    kind: 'fish',
  },
  {
    keyword: 'ramen',
    name: 'Рамен',
    price: 375,
    category: 'soup',
    count: '425 г',
    image: 'img/ramen.webp',
    kind: 'meat',
  },
  {
    keyword: 'tom_yam',
    name: 'Том ям с креветками',
    price: 650,
    category: 'soup',
    count: '500 г',
    image: 'img/tom_yam.webp',
    kind: 'fish',
  },
  {
    keyword: 'chicken_soup',
    name: 'Куриный суп',
    price: 330,
    category: 'soup',
    count: '350 г',
    image: 'img/chicken_soup.webp',
    kind: 'meat',
  },
  {
    keyword: 'corean_salad',
    name: 'Корейский салат с овощами и яйцом',
    price: 330,
    category: 'starter',
    count: '250 г',
    image: 'img/corean_salad.webp',
    kind: 'veg',
  },
  {
    keyword: 'ceasar',
    name: 'Цезарь с цыпленком',
    price: 370,
    category: 'starter',
    count: '220 г',
    image: 'img/ceasar.webp',
    kind: 'meat',
  },
  {
    keyword: 'caprese',
    name: 'Капрезе с моцареллой',
    price: 350,
    category: 'starter',
    count: '235 г',
    image: 'img/caprese.webp',
    kind: 'veg',
  },
  {
    keyword: 'tuna_salad',
    name: 'Салат с тунцом',
    price: 480,
    category: 'starter',
    count: '250 г',
    image: 'img/tuna_salad.webp',
    kind: 'fish',
  },
  {
    keyword: 'fries_ceasar',
    name: 'Картофель фри с соусом цезарь',
    price: 280,
    category: 'starter',
    count: '235 г',
    image: 'img/fries_ceasar.webp',
    kind: 'veg',
  },
  {
    keyword: 'fries_catchup',
    name: 'Картофель фри с кетчупом',
    price: 260,
    category: 'starter',
    count: '235 г',
    image: 'img/fries_catchup.webp',
    kind: 'veg',
  },
  {
    keyword: 'potatoes',
    name: 'Жареная картошка с грибами',
    price: 330,
    category: 'main',
    count: '250 г',
    image: 'img/potatoes.jpg',
    kind: 'veg',
  },
  {
    keyword: 'funchosa',
    name: 'Фунчоза по-корейски с овощами и грибами',
    price: 280,
    category: 'main',
    count: '250 г',
    image: 'img/funchosa.webp',
    kind: 'veg',
  },
  {
    keyword: 'lasagna',
    name: 'Лазанья',
    price: 385,
    category: 'main',
    count: '310 г',
    image: 'img/lasagna.jpg',
    kind: 'meat',
  },
  {
    keyword: 'chicken_patty',
    name: 'Котлеты из курицы с картофельным пюре',
    price: 225,
    category: 'main',
    count: '280 г',
    image: 'img/chicken_patty.jpg',
    kind: 'meat',
  },
  {
    keyword: 'fish_patty',
    name: 'Рыбная котлета с рисом и спаржей',
    price: 320,
    category: 'main',
    count: '270 г',
    image: 'img/fish_patty.webp',
    kind: 'fish',
  },
  {
    keyword: 'shrimps_pasta',
    name: 'Паста с креветками',
    price: 340,
    category: 'main',
    count: '280 г',
    image: 'img/shrimps_pasta.webp',
    kind: 'fish',
  },
  {
    keyword: 'orange',
    name: 'Апельсиновый сок',
    price: 120,
    category: 'drink',
    count: '300 мл',
    image: 'img/orange.jpg',
    kind: 'cold',
  },
  {
    keyword: 'apple',
    name: 'Яблочный сок',
    price: 90,
    category: 'drink',
    count: '300 мл',
    image: 'img/apple.webp',
    kind: 'cold',
  },
  {
    keyword: 'carrot',
    name: 'Морковный сок',
    price: 110,
    category: 'drink',
    count: '300 мл',
    image: 'img/carrot.jpg',
    kind: 'cold',
  },
  {
    keyword: 'capuchino',
    name: 'Капучино',
    price: 180,
    category: 'drink',
    count: '300 мл',
    image: 'img/capuchino.webp',
    kind: 'hot',
  },
  {
    keyword: 'green_tea',
    name: 'Зеленый чай',
    price: 100,
    category: 'drink',
    count: '300 мл',
    image: 'img/green_tea.webp',
    kind: 'hot',
  },
  {
    keyword: 'black_tea',
    name: 'Черный чай',
    price: 90,
    category: 'drink',
    count: '300 мл',
    image: 'img/black_tea.webp',
    kind: 'hot',
  },
  {
    keyword: 'pahlava',
    name: 'Пахлава',
    price: 220,
    category: 'desert',
    count: '300 гр',
    image: 'img/pahlava.webp',
    kind: 'medium',
  },
  {
    keyword: 'cheese',
    name: 'Чизкейк',
    price: 240,
    category: 'desert',
    count: '125 гр',
    image: 'img/cheese.webp',
    kind: 'small',
  },
  {
    keyword: 'choko_cheese',
    name: 'Шоколадный чизкейк',
    price: 260,
    category: 'desert',
    count: '125 гр',
    image: 'img/choko_cheese.webp',
    kind: 'small',
  },
  {
    keyword: 'choko_cake',
    name: 'Шоколадный торт',
    price: 270,
    category: 'desert',
    count: '140 гр',
    image: 'img/choko_cake.webp',
    kind: 'small',
  },
  {
    keyword: 'donuts3',
    name: 'Пончики (3 штуки)',
    price: 410,
    category: 'desert',
    count: '350 гр',
    image: 'img/donuts3.webp',
    kind: 'medium',
  },
  {
    keyword: 'donuts6',
    name: 'Пончики (6 штук)',
    price: 650,
    category: 'desert',
    count: '700 гр',
    image: 'img/donuts6.webp',
    kind: 'big',
  },
];
