const menuItems = [
  {
    keyword: 'gaspacho',
    name: 'Гаспачо',
    price: 195,
    category: 'soup',
    count: '350 г',
    image: 'img/gaspacho.jpg',
  },
  {
    keyword: 'mashroom_soup',
    name: 'Грибной суп-пюре',
    price: 185,
    category: 'soup',
    count: '330 г',
    image: 'img/mashroom_soup.jpg',
  },
  {
    keyword: 'norway_soup',
    name: 'Норвежский суп',
    price: 270,
    category: 'soup',
    count: '330 г',
    image: 'img/norway_soup.jpg',
  },
  {
    keyword: 'potatoes',
    name: 'Жареная картошка с грибами',
    price: 150,
    category: 'main',
    count: '250 г',
    image: 'img/potatoes.jpg',
  },
  {
    keyword: 'lasagna',
    name: 'Лазанья',
    price: 385,
    category: 'main',
    count: '310 г',
    image: 'img/lasagna.jpg',
  },
  {
    keyword: 'patty',
    name: 'Котлеты из курицы с картофельным пюре',
    price: 225,
    category: 'main',
    count: '280 г',
    image: 'img/patty.jpg',
  },
  {
    keyword: 'orange',
    name: 'Апельсиновый сок',
    price: 120,
    category: 'drink',
    count: '300 мл',
    image: 'img/orange.jpg',
  },
  {
    keyword: 'apple',
    name: 'Яблочный сок',
    price: 90,
    category: 'drink',
    count: '300 мл',
    image: 'img/apple.webp',
  },
  {
    keyword: 'carrot',
    name: 'Морковный сок',
    price: 110,
    category: 'drink',
    count: '300 мл',
    image: 'img/carrot.jpg',
  },
];
